[package]
authors = ["Noskcaj <kcajdev@gmail.com>"]
name = "ded"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
serde = "1.0.33"
serde_derive = "1.0.33"
toml = "0.4.5"
rustbox = "0.11.0"
lazy_static = "1.0.0"
chrono = "0.4.2"

[dependencies.serenity]
git = "https://github.com/Noskcaj19/serenity.git"
